name: network_search
description: A new Flutter package project.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  equatable: ^1.0.1
  flutter_bloc: ^2.1.1
  json_annotation: ^3.0.1
  diacritic: ^0.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.8.1
  json_serializable: ^3.3.0
  mockito: ^4.1.1
  bloc_test: ^2.2.2

flutter:
  assets:
    - assets/
