name: network_search
description: A new Flutter package project.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  equatable: ^1.0.1
  flutter_bloc: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
